import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'
import Announcement from '@/components/announcement'
import Navbar from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const navLinks = [
    { label: 'All courses', href: '/all-courses' },
    { label: 'New courses', href: '/new-courses' },
    { label: 'Free courses', href: '/free-courses' },
  ]

  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navbar path='/' pathName='blog.mosespace' navLinks={navLinks} />
        <Announcement
          buttonInfo='Support on Youtube!'
          description='Launched on Youtube! If you like the content we give here, please support me by subscribing to my youtube @codewithmoses today.'
        />
        {children}
      </body>
    </html>
  )
}
